
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

public class ResumeGeneratorService
{
    public byte[] GenerateResume(CandidateRegisterDto dto)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(12).FontFamily("Arial"));

                // Header
                page.Header().Background("#E3F2FD").Padding(10)
                    .Text("RESUME")
                    .FontSize(28)
                    .Bold()
                    .FontColor("#1565C0")
                    .AlignCenter();

                // Content
                page.Content().Column(col =>
                {
                    col.Spacing(15);

                    // Personal Info
                    col.Item().Row(row =>
                    {
                        row.RelativeColumn().Text($"Name: {dto.FullName}").FontSize(14).Bold();
                        row.RelativeColumn().Text($"Email: {dto.Email}").FontSize(14).Bold();
                    });

                    col.Item().LineHorizontal(1).LineColor("#BBDEFB");

                    // Skills
                    col.Item().Text("Skills").FontSize(18).Bold().FontColor("#0D47A1");
                    col.Item().Text(dto.SkillSet).FontSize(13);

                    // Experience
                    col.Item().Text("Experience").FontSize(18).Bold().FontColor("#0D47A1");
                    col.Item().Text($"{dto.TotalYearsOfExperience} years").FontSize(13);

                    // Education
                    col.Item().Text("Education").FontSize(18).Bold().FontColor("#0D47A1");
                    col.Item().Text($"{dto.RecentEducation} at {dto.UniversityName}").FontSize(13);
                    col.Item().Text($"CGPA: {dto.AverageCGPA}").FontSize(13);

                    // Projects
                    if (dto.Projects?.Count > 0)
                    {
                        col.Item().Text("Projects").FontSize(18).Bold().FontColor("#0D47A1");
                        col.Item().Column(list =>
                        {
                            foreach (var project in dto.Projects)
                                list.Item().Text($"• {project}").FontSize(13);
                        });
                    }

                    // Internships
                    if (dto.Internships?.Count > 0)
                    {
                        col.Item().Text("Internships").FontSize(18).Bold().FontColor("#0D47A1");
                        col.Item().Column(list =>
                        {
                            foreach (var internship in dto.Internships)
                                list.Item().Text($"• {internship}").FontSize(13);
                        });
                    }
                });

                // Footer
                page.Footer().AlignCenter()
                    .Text("Generated by Interview Portal")
                    .FontSize(10)
                    .FontColor("#9E9E9E");
            });
        });

        return document.GeneratePdf();
    }
}
