using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

public class OfferLetterGenerator
{
    public byte[] GenerateOfferLetter(string candidateName, string position, decimal salary)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontFamily("Segoe UI").FontSize(12));

                page.Header()
                    .Text("OFFER LETTER")
                    .SemiBold().FontSize(26).FontColor("#2d6cdf").AlignCenter();

                page.Content()
                    .Column(col =>
                    {
                        col.Spacing(15);

                        col.Item().AlignRight().Text($"Date: {DateTime.Now:dd MMM yyyy}")
                            .FontSize(11).FontColor("#666");

                        col.Item().Text($"Dear {candidateName},")
                            .FontSize(13).SemiBold();

                        col.Item().Text(text =>
                        {
                            text.Span("Congratulations! We are pleased to offer you the position of ");
                            text.Span(position).Bold().FontColor("#2d6cdf");
                            text.Span(" at our organization.");
                        });

                        col.Item().Text(text =>
                        {
                            text.Span("Your starting salary will be ");
                            text.Span($"{salary:C}").Bold().FontColor("#2d6cdf");
                            text.Span(" per month.");
                        });

                        col.Item().Text("Please confirm your acceptance of this offer by replying to this email within this week.");

                        col.Item().Text("We look forward to welcoming you to our team!");

                        col.Item().Text("Best Regards,").FontSize(12);

                        col.Item().Text("HR Team").FontSize(12).Bold().FontColor("#2d6cdf");
                    });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by Interview Management Portal")
                    .FontSize(10).FontColor("#aaa");
            });
        });

        return document.GeneratePdf();
    }

}